source 'https://github.com/CocoaPods/Specs.git'
platform :ios ,'6.0'

pod 'DCIntrospect'
pod 'GHUnitIOS'
pod 'BlocksKit'
pod 'Underscore.m'
pod 'AQGridView'
pod 'QuickDialog'
pod 'JASidePanels'
pod 'OCCalendar'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'Reachability'
pod 'AFNetworking'
pod 'MagicalRecord'
pod 'NoticeView'
pod 'ELCImagePickerController'
pod 'LUKeychainAccess'
